import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const scriptDirectory = dirname(fileURLToPath(import.meta.url));
const root = join(scriptDirectory, "..");
const html = await readFile(join(root, "src", "webframe.html"), "utf8");
const engine = await readFile(join(root, "src", "schedule-engine.js"), "utf8");
const rateHtml = await readFile(join(root, "src", "rate-webframe.html"), "utf8");
const rateEngine = await readFile(join(root, "src", "rate-engine.js"), "utf8");
const output = [
  "// Generated by scripts/embed-assets.mjs. Do not edit directly.",
  `export const scheduleWebframeHtml = ${JSON.stringify(html)};`,
  `export const scheduleEngineJavaScript = ${JSON.stringify(engine)};`,
  `export const rateWebframeHtml = ${JSON.stringify(rateHtml)};`,
  `export const rateEngineJavaScript = ${JSON.stringify(rateEngine)};`,
  "",
].join("\n");

await writeFile(join(root, "src", "generated-assets.ts"), output, "utf8");
console.log("Embedded the guide-tool assets for GitBook publishing.");
